import os

# path to the xpcc root directory
softwareRootPath = '../'
xpccPath                = os.path.join(softwareRootPath, 'xpcc')

env = Environment(tools = ['xpcc'], toolpath = [xpccPath + '/scons/site_tools'])
env.Append(CPPPATH = ['.'])

# find all source files
files = env.FindFiles('.')

# build the xpcc library
env.XpccLibrary()

# build the program
program = env.Program(target = env['XPCC_CONFIG']['general']['name'], source = files.sources)

# create a file called 'defines.hpp' with all preprocessor defines if necessary
env.Defines()

env.Alias('size', env.Size(program))
env.Alias('symbols', env.Symbols(program))
env.Alias('defines', env.ShowDefines())

hexfile = env.Hex(program)

env.Alias('program', env.OpenOcd(program))
env.Alias('remote', env.OpenOcdRemote(hexfile))
env.Alias('build', [hexfile, env.Listing(program)])
env.Alias('all', ['build', 'size'])

env.Default('all')
